spring.application.name=Plat

spring.datasource.url=jdbc:mysql://localhost:3306/plat_db
spring.datasource.username=root
spring.datasource.password=sc5iupNu
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.application.name=boutique

server.port=8080
